### ISSUE TITLE
Create Form Backend For Sentiment Widget

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/warmup-exercise#1]
Team: BackEnd Team

Create a New File in root: dummy_form.html

Branch of: DEV

TODOs:
- [x] Create dummy_form.html file in root dir
- [x] add a dummy form submission to an HTML file (This form is just a basic form with no visual elements. All visual elements are by the front-end team)
- [x] Ensure the form has three parts and make it as minimally functional.
- [x] part (1) name and email box
- [x] part (2) Feedback section which is a free response (limit to 300 words) question
- [x] part (3) Sentiment Response based on 5 levels (1,2,3,4,5)
- [ ] #4
- [x] all files should be saved in a folder called (submissions)
- [x] save metadata if possible (right now just save date and time of submission)
- [ ] Ensure each element has tests

**Comment by nedbitar** [comment]
The JSON object is being created correctly right now. All someone has to do is save this into the submissions folder file, and implement a time and date option to it.
