### ISSUE TITLE
Create FrontEnd for Sentiment Widget

### ISSUE THREAD

**Issue by AdvaithRavishankar** [cse110-sp24-group15/warmup-exercise#2]
Team: FrontEnd Team

Create a New File in root: Sentiment_Widget.html

Branch of: DEV

TODOs:
- [ ] Create Sentiment_Widget.html file in the root directory
- [x] add a Form with the following elements:
- [x] part (1) name and email box
- [x] part (2) Feedback section which is a free response (limit to 300 words) question
- [x] part (3) Sentiment Response based on 5 levels (1,2,3,4,5)
- [x] Make sure each sentiment level is visual and accessible on any device
- [x] Make sure there is a fallback visual without Java Script
- [x] make the form visually appealing
- [x] Ensure CSS is commented well

**Comment by nedbitar** [comment]
You can use our form instead of creating your own. This would assist in the merging of the two codes. At the very least use the same ids.
